import { Injectable } from '@angular/core';
import { of } from 'rxjs';
import { HttpResponseData } from '../../app/core/types/api.interface';
import { Entity } from '../../app/shared/entities/base/entity.interface';
import { EntityFactory } from '../factories/base/entity.factory';

/**
 * Creates a mock service class extending a given base service.
 * The mock service has Jasmine spies for `index`, `show`, and `update` methods,
 * which return observable mock data generated by the provided factory.
 *
 * @template T - The entity type, must extend Entity.
 * @template S - The base service type to extend.
 * @param BaseService - The base service class to extend.
 * @param factory - Factory used to generate mock entity data.
 * @param overrides - Optional overrides for index, show, and update methods.
 * @returns A mock service class extending BaseService.
 *
 * @example
 * const MockUserService = mockServiceClass(UserService, userFactory, {
 *   index: { roles_count: 1 },
 *   show: { roles_count: 2 },
 *   update: { roles_count: 3 }
 * });
 * TestBed.configureTestingModule({
 *   providers: [{ provide: UserService, useClass: MockUserService }]
 * });
 */
export function mockServiceClass<T extends Entity, S extends { new (...args: any[]): any }>(
  BaseService: S,
  factory: EntityFactory<T>,
  overrides?: { index?: Partial<T>; show?: Partial<T>; update?: Partial<T> },
) {
  @Injectable()
  class Mock extends BaseService {
    index = jasmine.createSpy('index').and.callFake((params?: any) => {
      const data = [factory.create({ ...(overrides?.index ?? {}) } as Partial<T>)];
      return of({ data } as HttpResponseData<T[]>);
    });

    show = jasmine.createSpy('show').and.callFake((id: number, params?: any) => {
      const data = [factory.create({ id, ...(overrides?.show ?? {}) } as Partial<T>)];
      return of({ data } as HttpResponseData<T[]>);
    });

    update = jasmine
      .createSpy('update')
      .and.callFake((id: number, payload: Partial<T>, params?: any) => {
        const data = {
          ...factory.create({ id, ...(overrides?.update ?? {}) } as Partial<T>),
          ...payload,
        };
        return of({ data } as HttpResponseData<T>);
      });
  }

  return Mock;
}
